SELECT A1.ORDER_DT, A1.ITEM_CODE, '#1' CUST_CODE, A1.ORDER_UNIT, CONVERT(VARCHAR,MAX(C1.ORDER_EA_UNIT)) +'/'+ MAX(A1.ORDER_UNIT) ORDER_EA_UNIT,
  SUM(A1.PICK_QTY) PICK_QTY, MAX('전체') CUST_NAME, MAX('91') CELL_RESTORE, MAX(B1.ITEM_GUBUN) ITEM_GUBUN
FROM PD120 A1, MT300 B1, PM100 C1
WHERE A1.ITEM_CODE=B1.ITEM_CODE 
  AND A1.ORDER_TYPE = C1.ORDER_TYPE
  AND A1.ORDER_NO = C1.ORDER_NO
  AND A1.ITEM_CODE = C1.ITEM_CODE
  AND A1.ORDER_UNIT = C1.ORDER_UNIT
  AND A1.ORDER_DT ='20160119-001' --:ORDER_DT
  --AND B1.ITEM_CODE = '0410384'
  --AND A1.ORDER_STAT = '13'
GROUP BY A1.ORDER_DT, A1.ITEM_CODE, A1.ORDER_UNIT
UNION ALL

SELECT H2.ORDER_DT, H2.ITEM_CODE, '#2' CUST_CODE, H2.ORDER_UNIT, '0' ORDER_EA_UNIT,
  SUM(H2.PICK_QTY) PICK_QTY, MAX(H2.CUST_NAME) CUST_NAME, MAX(H2.CELL_RESTORE) CELL_RESTORE,MAX(H2.ITEM_GUBUN) ITEM_GUBUN
FROM (
  SELECT A2.*, '#2' CUST_CODE, '92' CELL_RESTORE, '좌측' CUST_NAME ,B1.ITEM_GUBUN
  FROM PD120 A2, PM100 B2, PD126 C2, MT300 B1
  WHERE A2.ITEM_CODE=B1.ITEM_CODE
    AND A2.ORDER_DT = '20160119-001' --:ORDER_DT
    --AND B1.ITEM_CODE = '0410384'
    --AND A2.ORDER_STAT = '13'
    AND A2.ORDER_TYPE = B2.ORDER_TYPE
    AND A2.ORDER_NO = B2.ORDER_NO
    AND A2.ITEM_CODE = B2.ITEM_CODE
    AND A2.ORDER_UNIT = B2.ORDER_UNIT
    AND A2.ORDER_DT = C2.ORDER_DT
    AND B2.CUST_CODE = C2.CUST_CODE
    AND C2.CELL_RESTORE < '25'
) H2
GROUP BY H2.ORDER_DT, H2.ITEM_CODE, H2.ORDER_UNIT
UNION ALL

SELECT H3.ORDER_DT, H3.ITEM_CODE, '#3' CUST_CODE, H3.ORDER_UNIT, '0' ORDER_EA_UNIT,
  SUM(H3.PICK_QTY) PICK_QTY, MAX(H3.CUST_NAME) CUST_NAME, MAX(H3.CELL_RESTORE) CELL_RESTORE,MAX(H3.ITEM_GUBUN) ITEM_GUBUN
FROM (
  SELECT A3.*, '#3' CUST_CODE, '93' CELL_RESTORE, '우측' CUST_NAME,B1.ITEM_GUBUN
  FROM PD120 A3, PM100 B3, PD126 C3,MT300 B1
  WHERE A3.ITEM_CODE=B1.ITEM_CODE
    AND A3.ORDER_DT = '20160119-001' --:ORDER_DT
    --AND B1.ITEM_CODE = '0410384'
    --AND A3.ORDER_STAT = '13'
    AND A3.ORDER_TYPE = B3.ORDER_TYPE
    AND A3.ORDER_NO = B3.ORDER_NO
    AND A3.ITEM_CODE = B3.ITEM_CODE
    AND A3.ORDER_UNIT = B3.ORDER_UNIT
    AND A3.ORDER_DT = C3.ORDER_DT
    AND B3.CUST_CODE = C3.CUST_CODE
    AND C3.CELL_RESTORE >= '25'
) H3
GROUP BY H3.ORDER_DT, H3.ITEM_CODE, H3.ORDER_UNIT
UNION ALL

SELECT H.ORDER_DT, H.ITEM_CODE, H.CUST_CODE, H.ORDER_UNIT, '0' ORDER_EA_UNIT,
  SUM(H.PICK_QTY) PICK_QTY, MAX(H.CUST_NAME) CUST_NAME, MAX(H.CELL_RESTORE) CELL_RESTORE,MAX(H.ITEM_GUBUN) ITEM_GUBUN
FROM (
  SELECT A.*, B.CUST_CODE, C.CELL_RESTORE, D.CUST_NAME,B1.ITEM_GUBUN
  FROM PD120 A, PM100 B, PD126 C, MT200 D,MT300 B1
  WHERE A.ITEM_CODE=B1.ITEM_CODE
    AND A.ORDER_DT = '20160119-001' --:ORDER_DT
    --AND B1.ITEM_CODE = '0410384'
    --AND A.ORDER_STAT = '13'
    AND A.ORDER_TYPE = B.ORDER_TYPE
    AND A.ORDER_NO = B.ORDER_NO
    AND A.ITEM_CODE = B.ITEM_CODE
    AND A.ORDER_UNIT = B.ORDER_UNIT
    AND A.ORDER_DT = C.ORDER_DT
    AND B.CUST_CODE = C.CUST_CODE
    AND C.CUST_CODE = D.CUST_CODE
    AND D.CUST_GUBUN = '2000'
) H
GROUP BY H.ORDER_DT, H.ITEM_CODE, H
.CUST_CODE, H.ORDER_UNIT

