UPDATE PD120
SET ORDER_STAT = '13',
      SORT_QTY = 0,
      D_ID = :D_ID,
      D_DATE = CONVERT(VARCHAR(20),GETDATE(),120)
WHERE ORDER_DT = :ORDER_DT
  AND ITEM_CODE = :ITEM_CODE
  AND ORDER_STAT = '15'
